### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm

###


### POST 请求测试注册接口
POST http://127.0.0.1:5000/register
Content-Type: application/json

{

  "account": "testuser2",
  "password": "1234"
}

###

### POST 请求测试登录接口
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "account": "testuser2",
  "password": "123"
}
###

### GET 请求浏览今日菜品信息
GET http://127.0.0.1:5000/daily-menu
{
  "menu": [
    {
      "id": "1",
      "name": "宫保鸡丁",
      "price": 30,
      "description": "经典川菜，鸡肉嫩滑，花生香脆"
    },
    {
      "id": "2",
      "name": "鱼香肉丝",
      "price": 28,
      "description": "四川特色菜，酸甜适中，肉丝嫩滑"
    }
  ]
}

### POST 请求在线订餐
POST http://127.0.0.1:5000/order
Content-Type: application/json

{
  "items": [
    {
      "id": "1",
      "quantity": 2
    },
    {
      "id": "2",
      "quantity": 1
    }
  ]
}

### GET 请求浏览座位信息
GET http://127.0.0.1:5000/seats
{
  "seats": [
    {
      "id": "1",
      "status": "available",
      "location": "A区，第一排"
    },
    {
      "id": "2",
      "status": "available",
      "location": "B区，第二排"
    },
    {
      "id": "3",
      "status": "booked",
      "location": "C区，第三排"
    }
  ]
}

### POST 请求预订座位
POST http://127.0.0.1:5000/book-seat
Content-Type: application/json

{
  "seat_id": "1"
}
